#!/usr/bin/env node
/**
 * Convert the Emscripten glue JS (syntaqlite-runtime.js) into an ES module
 * that can be imported in Cloudflare Workers.
 *
 * The upstream glue JS is a non-modularized script that:
 * - Sets `var Module = typeof Module != 'undefined' ? Module : {};`
 * - Uses `document.createElement("script")` and `window.Module`
 * - Calls `run()` immediately at the end
 *
 * This script wraps it in an async factory function that:
 * - Accepts a Module config object (with wasmBinary pre-loaded)
 * - Returns a Promise<EmscriptenModule> resolved via onRuntimeInitialized
 * - Removes browser-specific APIs (document, window references)
 *
 * Usage: node scripts/convert-glue.mjs
 * Input:  wasm/syntaqlite-runtime.js
 * Output: wasm/syntaqlite-runtime.mjs
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(__dirname, "..");
const inputPath = resolve(pkgRoot, "wasm/syntaqlite-runtime.js");
const outputPath = resolve(pkgRoot, "wasm/syntaqlite-runtime.mjs");

let source = readFileSync(inputPath, "utf-8");

// 1. Replace the Module declaration to use the passed-in config
source = source.replace(
	"var Module = typeof Module != 'undefined' ? Module : {};",
	"// Module is provided by the factory wrapper",
);

// 2. Remove the `module['exports'] = Module;` Node.js export (line ~97)
source = source.replace(
	/if\s*\(typeof module != 'undefined'\)\s*\{\s*module\['exports'\]\s*=\s*Module;\s*\}/,
	"// module.exports removed — using ES module export",
);

// 3. Guard document references — Workers have no document
source = source.replace(
	/var _scriptName = typeof document != 'undefined' \? document\.currentScript\?\.src : undefined;/,
	"var _scriptName = undefined;",
);

// 4. Guard window references in HEAPU8 fallback
source = source.replace(
	/var heap = this\.module!\.HEAPU8 \|\| window\.HEAPU8;/g,
	"var heap = this.module.HEAPU8;",
);

// 5. Wrap in a factory function and export
const wrapped = `// Auto-generated by scripts/convert-glue.mjs — do not edit manually.
// Source: syntaqlite-runtime.js (Emscripten glue for syntaqlite WASM)

export default function createSyntaqliteModule(moduleConfig) {
  return new Promise((resolve, reject) => {
    var Module = moduleConfig || {};

    // Wire up the resolution callback
    var origCallback = Module['onRuntimeInitialized'];
    Module['onRuntimeInitialized'] = function() {
      if (origCallback) origCallback();
      resolve(Module);
    };
    var origAbort = Module['onAbort'];
    Module['onAbort'] = function(reason) {
      if (origAbort) origAbort(reason);
      reject(new Error('syntaqlite WASM aborted: ' + reason));
    };

    // --- Begin Emscripten glue ---
    ${source}
    // --- End Emscripten glue ---
  });
}
`;

writeFileSync(outputPath, wrapped, "utf-8");
console.log(`Wrote ${outputPath}`);
console.log(`Size: ${(wrapped.length / 1024).toFixed(1)} KB`);
